Engine as visitor
cqframework/clinical_quality_language pull request #1165
Opened 2023-05-02 19:56 UTC by mdnazmulkarim

2023-06-13 13:28 UTC, brynrhodes requested changes
This looks fantastic, nice work! I like the rename of runtime context to State, and I like the introduction of the Environment. The only comment I have is that we should update the comment on the CqlEngine class to document that we switched from a deserialization approach to a visitor approach, since the documentation still says we're opting for the deserialization approach.

2023-06-22 18:26 UTC, JPercival commented on Src/java/engine/src/main/java/org/opencds/cqf/cql/engine/elm/visiting/FunctionRefEvaluator.java
> +    private FunctionDef cachedFunctionDef;
Making this an instance breaks the function caching. We should make this class static, and add a  `Map<FunctionRef, FunctionDef> functionCache` the `State` object. Then this evaluator should be able to use/update the state as needed to resolve the cache.

2023-06-22 18:27 UTC, JPercival commented on Src/java/engine/src/main/java/org/opencds/cqf/cql/engine/elm/visiting/QueryEvaluator.java
This class can be used statically.

2023-06-22 18:33 UTC, JPercival commented on Src/java/engine/src/main/java/org/opencds/cqf/cql/engine/elm/visiting/ExpressionDefEvaluator.java
> +            visitor.processException(e, expressionDef);
`processException` sneakily throws an exception. We should make that clear by calling it something like `throwExceptionWithSourceLocators` or by doing something like "throw addSourceLocatorsToException(e)"

Additionally, we should centralize the exception handling. It should only be done at the top-level `evaluate` method in the cql engine.

2023-06-22 18:36 UTC, JPercival commented on Src/java/engine/src/main/java/org/opencds/cqf/cql/engine/execution/CqlEngine.java
> +    public Object validateOperand(Object operand) {
It's unclear to me why we need this. Shouldn't `ExpressionDefs` be visited already when resolving the operand?

2023-06-22 18:40 UTC, JPercival commented on Src/java/engine/src/main/java/org/opencds/cqf/cql/engine/execution/CqlEngine.java
> +        } catch (Exception e) {
we should move exception handling up to a central location. All the visit methods should be trivial.

2023-06-22 18:41 UTC, JPercival commented on Src/java/engine/src/main/java/org/opencds/cqf/cql/engine/elm/visiting/FunctionRefEvaluator.java
> +    private FunctionDef cachedFunctionDef;
I mean the `Cache` object, not the `State` object.

2023-06-23 15:37 UTC, JPercival commented
Approved. Let's address the remaining issues as part of new PRs.

2023-06-26 22:34 UTC, brynrhodes approved these changes
Overall it looks really good and I'm comfortable it's at least as functional as the previous engine based on regressions

2023-06-26 23:13 UTC, merged