[WIP] CQL JS Compiler
cqframework/clinical_quality_language pull request #1462
Opened 2024-12-04 17:00 UTC by JPercival

* Conversion of Java code to Kotlin to use Kotlin Multiplatform to generate a JS CQL Compiler
* Tests and demo app for the above

2024-12-06 20:30 UTC, antvaset approved these changes

2025-03-11 00:09 UTC, cmoesel requested changes
**Code Review Part 1**

Given how much there is in this PR, I thought it might be helpful if I left my reviews in parts, as they are available. So here's the first set, which includes the `Cql2ElmVisitor`, which was a pretty big one!

2025-03-11 00:09 UTC, cmoesel commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/CqlCompiler.kt
> +
The Java source has a `getCompiledLibraries` function definition that appears to have been completely dropped in the Kotlin. Was that intentional? Did we decide we don't actually need it or want it? Are we sure no one was using it? (It is public)
```java
public Map<VersionedIdentifier, CompiledLibrary> getCompiledLibraries() {
    return libraryManager.getCompiledLibraries();
}
```

2025-03-11 00:09 UTC, cmoesel commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/CqlCompiler.kt
> +        messages?.addAll(builder.messages)
These are all assigned to ArrayLists on lines 147 - 150. Is there a way for them to possibly be null at this point?

2025-03-11 20:23 UTC, antvaset commented on Src/java/buildSrc/settings.gradle.kts
> +    id("org.gradle.toolchains.foojay-resolver-convention")
It won't let you add `version("0.8.0")` to buildSrc/settings.gradle.kts when you have `id("org.gradle.toolchains.foojay-resolver-convention") version("0.8.0")` in settings.gradle.kts. If you try, you end up declaring the plugin twice and get this

```
Error resolving plugin [id: 'org.gradle.toolchains.foojay-resolver-convention', version: '0.8.0']
> The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version, so compatibility cannot be checked.
```

What we have in the settings.gradle.kts file is for the entire build including buildSrc so setting the version settings.gradle.kts should be enough.

2025-03-12 09:03 UTC, antvaset commented on Src/java/buildSrc/src/main/kotlin/cql.xjc-temp-conventions.gradle.kts
This was a temporary plugin that generated the model info and elm classes using the old xjc alongside the new xsd-to-kotlin gen, to let us compare the autogenerated classes. It's removed in https://github.com/cqframework/clinical_quality_language/pull/1511. Sorry about that.

2025-03-12 09:33 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +)
Kotlin makes it easy to define helper and utility methods simply as top level `fun`'s, and we could use these to offload some logic from Cql2ElmVisitor.

2025-03-12 14:18 UTC, cmoesel commented on Src/java/buildSrc/settings.gradle.kts
> +    id("org.gradle.toolchains.foojay-resolver-convention")
Ah. It's been a while since I've done _anything_ with gradle. Thanks for the clarification.

2025-03-12 19:51 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +                    minute = matcher.groups[3]!!.value.toInt()
Kotlin doesn't do a smart cast to a non-nullable type here, similar to TypeScript. It's possible to have this though
```kotlin
val group = matcher.groups[3]
if (group != null) {
  minute = group.value.toInt()
  // ...
}
```

2025-03-12 20:50 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +                        (functionDef.expression!!.resultType != null)
I've simplified this condition to
```kotlin
if (resultType != null && functionDef.expression?.resultType != null) {
  // ...
}
```
in https://github.com/cqframework/clinical_quality_language/pull/1511. Thanks for pointing this out!

2025-03-12 20:51 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +                    require(subTypeOf(functionDef.expression!!.resultType, resultType.resultType)) {
Even in the simplified version
```kotlin
if (resultType != null && functionDef.expression?.resultType != null) {
  // ...
}
```
only `resultType` is smart-cast from `TypeSpecifier?` to ` TypeSpecifier`. `functionDef.expression` is still typed as `Expression?` in the body of the if statement.

2025-03-12 20:56 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/CqlCompiler.kt
> +
You're right! I added it back in https://github.com/cqframework/clinical_quality_language/pull/1511 as
```
val compiledLibraries: Map<VersionedIdentifier, CompiledLibrary>
  get() = libraryManager.compiledLibraries
```
which should bring back the getCompiledLibraries method. It looks like it's not used in this project but others could be using that because it's part of the public API.

2025-03-12 21:46 UTC, cmoesel requested changes
Here's another installment of comments and questions... Slowly making my way through this!

2025-03-12 21:46 UTC, cmoesel commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +                    require(subTypeOf(functionDef.expression!!.resultType, resultType.resultType)) {
Too bad. I wish it was smarter! Oh well...

2025-03-12 21:46 UTC, cmoesel commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +                    minute = matcher.groups[3]!!.value.toInt()
I see... So basically Kotlin will smart-cast a top-level variable, but won't smart-cast any nested members within a variable. I guess maybe it's harder to track re-assignments to nested members. Oh well.

I don't think it makes sense to introduce a local variable just to get smart casts, so no changes needed here.

2025-03-13 10:10 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +    }
I couldn't find any usages of `Cql2ElmVisitor`'s `getModel()` in this codebase either, but it's possible that someone who's extended `Cql2ElmVisitor` needs the original behavior because it's part of the `protected` API. Thanks for spotting this! I brought back the `if (modelName == null) { ... }` check in https://github.com/cqframework/clinical_quality_language/pull/1511 to be safe. I think it was removed in an effort to simplify the logic a bit.

2025-03-13 10:35 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +                    minute = matcher.groups[3]!!.value.toInt()
Thanks, I agree. It's not perfect.

2025-03-13 10:37 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +                    result.`else` = (parseExpression(pt))
Actually in Java we wouldn't be able to have a field called `else`!

2025-03-13 10:41 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +            require(!(sources.isNotEmpty() && !hasFrom)) {
I've fixed both `require`s in `visitSourceClause()` in https://github.com/cqframework/clinical_quality_language/pull/1511 to make them more readable.

2025-03-13 10:51 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +                (result.resolution!!.operator.libraryName == null ||
Yes, all of the `!!` are required here
```kotlin
if (
    result is FunctionRefInvocation &&
        result.resolution != null &&
        (result.resolution!!.operator.libraryName == null ||
            (result.resolution!!.operator.libraryName ==
                libraryBuilder.compiledLibrary.identifier!!.id))
        ) { ... }
```
because Kotlin only smart casts result from `Invocation?` to non-nullable `FunctionRefInvocation` after the first `is` check.

As we converted Java to Kotlin and many of the `!!` and `?.` showed up, we did some cleanup to fix the root causes of those, including making `operator` non-nullable in `OperatorResolution`:
```kotlin
data class OperatorResolution(var operator: Operator, val conversions: List<Conversion?>) { ... }
```
So you can't instantiate an `OperatorResolution` without a non-nullable operator, which seems reasonable.

2025-03-13 10:54 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +                    chunks = saveChunks
I agree, this is better for readability. Pushed to https://github.com/cqframework/clinical_quality_language/pull/1511.

2025-03-13 11:56 UTC, antvaset commented on Src/java/buildSrc/src/main/kotlin/cql.kotlin-multiplatform-conventions.gradle.kts
> +            }
I've pushed a small change to https://github.com/cqframework/clinical_quality_language/pull/1511 (https://github.com/cqframework/clinical_quality_language/pull/1511/commits/22bd49efbf251dcb3de66caea0a1cb5938f41eaf) to use exactly the configuration from https://kotlinlang.org/docs/js-running-tests.html.

Just checked to make sure it runs the JS tests in headless Chrome, using the cql subproject as an example. When you run the `cql:build` task, it builds and runs `cql:allTests`. If you add broken tests that throw exceptions at runtime under commonTest and jsTest, the task fails and it does show that commonTest tests failed on the [jvm] and commonTest and jsTest tests failed on [js, browser, ChromeHeadless134.0.0.0, MacOS10.15.7].

2025-03-14 11:39 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/SimpleLibraryManager.kt
> +                return null
It's to have a helper function that creates an instance of CommonLibraryManager to use in JS.

The design of the actual JS API is still work in progress, and currently this simple version of `@JsExport`-able `getSimpleLibraryManager()` accepts the `getLibraryCql: (id, system, version) -> string` callback that only provides the CQL source of the requested library (which was enough for the demo). When resolving libraries, the library manager calls `getLibraryContent()` first in an attempt to find pre-compiled ELM and if the method returns null, the library manager goes on to call `getLibrarySource()` and build from source.

I've added this to the code in https://github.com/cqframework/clinical_quality_language/pull/1514/commits/01424b549ac75f5ff09356ad7dadc554a2c0e449.

2025-03-14 12:08 UTC, antvaset commented on Src/java/buildSrc/src/main/kotlin/cql.library-conventions.gradle.kts
> +    signature("com.toasttab.android:gummy-bears-api-${project.findProperty("android.api.level")}:0.10.0:coreLib2@signature")
Thanks for noticing this! I've removed this line and other mentions of Jackson in https://github.com/cqframework/clinical_quality_language/pull/1514/commits/23984372ca7872db4a2a75d86a95cb5ea5d54022.

2025-03-14 12:48 UTC, cmoesel commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +                (result.resolution!!.operator.libraryName == null ||
OK. Thanks for the additional insight. I think when I was reviewing these I just had unfairly high expectations for Kotlin's smart casts. I'll try to stop commenting on these! ;-)

2025-03-17 20:02 UTC, cmoesel requested changes
Here's another (much smaller) set of comments and questions.

I am also no longer able to build this. When I run `./gradlew clean install`, I get errors like the following:
> Task :cql:generateKotlinGrammarSource FAILED
> error(50): cql.interp:1:0: syntax error: 'token' came as a complete surprise to me
> error(50): cql.interp:1:6: syntax error: missing SEMI at 'literal'
> error(50): cql.interp:1:14: syntax error: extraneous input 'names' expecting COLON while matching a rule
> ... (many more)

This is using JDK 17: Temurin-17.0.14+7 (build 17.0.14+7).

2025-03-18 10:54 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +        currentContext =
It does make sense in a large class like `Cql2ElmVisitor`. I've added `this.` in all cases for its own fields and those inherited from `CqlPreprocessorElmCommonVisitor` in https://github.com/cqframework/clinical_quality_language/pull/1514.

2025-03-18 19:22 UTC, JPercival commented on Src/java/cql-to-elm/src/jvmMain/kotlin/org/cqframework/cql/cql2elm/ModelManager.kt
> +        require(identifier.id.isNotEmpty()) { "Model identifier Id is required" }
I think the require in ModelManager can be removed, yes.

2025-03-18 19:22 UTC, JPercival commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/model/CompiledLibrary.kt
> +    }
I'm happy to toss all unused code.

2025-03-18 19:26 UTC, JPercival commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/model/ConversionMap.kt
> +        while (currentType != null && currentType != DataType.ANY) {
The way that `DataType.ANY` was defined in Java introduced a circular dependency between `SimpleType` and `DataType`. Kotlin is stricter than Java in that regard. So, I needed to redefine `DataType.ANY` and update several related checks, including this one.

2025-03-18 19:36 UTC, JPercival commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/LibraryBuilder.kt
> +        return compiledLibrary.resolveCall(callContext, conversionMap)?.operator
Comment should be updated. The null handling was tightened up such that passing in a null is no longer allowed:
https://github.com/cqframework/clinical_quality_language/pull/1462/files#diff-51925094c25bf8d484fb03bc4d26e951f07267f1d67205df7ba0f4af39c991daR226

2025-03-18 19:38 UTC, JPercival commented on Src/java/buildSrc/src/main/kotlin/cql.library-conventions.gradle.kts
> +    signature("com.toasttab.android:gummy-bears-api-${project.findProperty("android.api.level")}:0.10.0:coreLib2@signature")
This comment is _not_ saying we're using Jackson. It's saying that we're copying build patterns found in the Jackson project to address Android support. It references Jackson because it's a widely used and well-tested library and (in theory) what's working from them ought to work for us.

2025-03-18 19:41 UTC, JPercival commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +            ctx.start?.charPositionInLine?.inc() ?: 0, // 1-based instead of 0-based
The `.inc()` is the same as `+ 1`.

2025-03-18 19:43 UTC, JPercival commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +            ctx.start?.line ?: 0,
Essentially, yes. In Java the primitive `int` is initialized as 0, so the default value for the line is 0. Kotlin requires us to be explicit about that in the constructor of the Trackback. Another option would be to define a nullable secondary constructor on Trackback. This would make the code look more like the Java equivalent.

2025-03-18 19:55 UTC, JPercival commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/model/FunctionHeader.kt
> +                }
Yes, I intended that as an improvement to make the mangledName more readable in cases where types had names. `mangledName` essentially works as a hashing function to determined if there are potential conflicts with overloads. CQL is nominally typed in most cases, so the name is actually better than the type signature.

2025-03-18 20:38 UTC, cmoesel commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +            ctx.start?.charPositionInLine?.inc() ?: 0, // 1-based instead of 0-based
Oh. Duh. It just didn't pop out in the diff the same way the `+ 1` did. Sorry about that!

2025-03-18 20:55 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +                .withValue(parseExpression(ctx.expression()))
Have a look at https://github.com/cqframework/clinical_quality_language/commit/44f4bdf012124fc06a5b1badfe2a56ffc7910006 (particularly changes to Trackable.kt). Same as before, `Trackable` is used to provide the `trackerId`, `trackbacks`, `resultType` fields to child classes. It was changed from a superclass of all ELM classes to a collection of Kotlin extension properties on `Element` and its children. `TupleElement`, `VersionedIdentifier`, `InstanceElement` don't extend `Element` so they don't have those extra fields anymore. To track / process result types in the code, we still use `DataType` and its children (see classes under /Src/java/model/src/commonMain/kotlin/org/hl7/cql/model) which include `TupleType`with `TupleTypeElement` elements each of which has a `type` field.

2025-03-18 22:23 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +        // (NamedType)classType.getBaseType();
He-he, I've cleaned it up to change it into prose in https://github.com/cqframework/clinical_quality_language/pull/1514/commits/efae0efae958af797ff61eea02d93edca2b0c361.

2025-03-18 22:24 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +                    // Last(Split(MR.medication.reference, '/')) and M.code in <valueset>
This is cleaned up together with other comments in `Cql2ElmVisitor` in https://github.com/cqframework/clinical_quality_language/pull/1514/commits/efae0efae958af797ff61eea02d93edca2b0c361.

2025-03-18 22:31 UTC, antvaset commented on Src/java/buildSrc/src/main/kotlin/cql.library-conventions.gradle.kts
> +    signature("com.toasttab.android:gummy-bears-api-${project.findProperty("android.api.level")}:0.10.0:coreLib2@signature")
I've added it back in https://github.com/cqframework/clinical_quality_language/pull/1514.

2025-03-19 12:25 UTC, cmoesel commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +        var codeComparator: String? = codeComparator
Based on seeing this pattern in a lot of other places, I'm guessing that my hunch was correct. So I'm resolving this.

2025-03-19 13:20 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/Cql2ElmVisitor.kt
> +            }
To me `requireNotNull` looks better than adding `!= null`, so why not? :) I've cleaned up all require's in https://github.com/cqframework/clinical_quality_language/pull/1514/commits/eebc8555e8041be40293939c85b671d1dd174abe.

`Invocation.expression` is non-nullable in the refactored version, see https://github.com/cqframework/clinical_quality_language/blob/fc5fe0274c3acd402bb619c3f7bbae697b52caaf/Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/model/Invocation.kt#L25 .

2025-03-20 09:12 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/CqlCompiler.kt
> +        messages?.addAll(builder.messages)
Yes, however `this.exceptions`, `this.errors`, `this.warnings`, and `this.messages` still have nullable types (`MutableList<CqlCompilerException>?`) even after we've assigned non-nulls to them. I.e. Kotlin doesn't change the type of class fields here.
The only way to avoid `?.` here is to introduce 4 local variables, which is not ideal either.

2025-03-20 09:20 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/ModelManager.kt
> +    fun resolveModel(modelName: String, version: String? = null): Model
Technically there is a difference for Java uses because if we only had the 2-arg overload (even with the second parameter having a default value), in Java you would always need to pass two args. So there are two overloads here, for backwards compatibility. Alternatively we could have
```
@JvmOverloads
fun resolveModel(modelName: String, version: String? = null): Model
```
which would generate the first overload automatically for Java.

2025-03-20 09:23 UTC, antvaset commented on Src/java/cql-to-elm/src/jvmMain/kotlin/org/cqframework/cql/cql2elm/ModelManager.kt
> +
Yeah, we'll have to re-think the API for this class and maybe simplify the constructors.

2025-03-20 09:26 UTC, antvaset commented on Src/java/cql-to-elm/src/jvmMain/kotlin/org/cqframework/cql/cql2elm/ModelManager.kt
> +        require(identifier.id.isNotEmpty()) { "Model identifier Id is required" }
I've deleted the redundant require in https://github.com/cqframework/clinical_quality_language/pull/1514.

2025-03-20 09:29 UTC, antvaset commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/model/CompiledLibrary.kt
> +    }
This is cleaned up in https://github.com/cqframework/clinical_quality_language/pull/1514.

2025-03-20 14:39 UTC, brynrhodes approved these changes

2025-03-20 15:52 UTC, JPercival commented on Src/java/cql-to-elm/src/commonMain/kotlin/org/cqframework/cql/cql2elm/CqlCompiler.kt
> +        messages?.addAll(builder.messages)
Given that Kotlin has properties, I think we just have one non-nullable mutable backing list, and expose `exceptions`, `errors`, `warnings` and `messages` as views on that backing list that just filters down to the appropriate type/level. I don't think we need to do that right now, but that would clean up all this quite a bit.

2025-03-21 12:34 UTC, antvaset commented
> Here's another (much smaller) set of comments and questions.
> 
> I am also no longer able to build this. When I run `./gradlew clean install`, I get errors like the following:
> 
> > Task :cql:generateKotlinGrammarSource FAILED
> > error(50): cql.interp:1:0: syntax error: 'token' came as a complete surprise to me
> > error(50): cql.interp:1:6: syntax error: missing SEMI at 'literal'
> > error(50): cql.interp:1:14: syntax error: extraneous input 'names' expecting COLON while matching a rule
> > ... (many more)
> 
> This is using JDK 17: Temurin-17.0.14+7 (build 17.0.14+7).

Hi @cmoesel, are you still experiencing issues with building locally? I haven't seen it fail on `:cql:generateKotlinGrammarSource`.

Also, I've just merged https://github.com/cqframework/clinical_quality_language/pull/1514 which included changes to Gradle that fixed build issues related to the XSD Kotlin codegen. Earlier today the builds were failing because s01.oss.sonatype.org was down but all green now.

2025-09-24 13:56 UTC, brynrhodes approved these changes

2025-09-24 18:06 UTC, cmoesel approved these changes
I'm not able to review the hundreds of files again, but based on the quality of code from past reviews, successful integration into the CQL Translation Service, and some initial success regression testing a set of our CQL libraries with this, and assuming this has undergone internal code review, I'm comfortable approving.

Amazing work, @JPercival and @antvaset. This is so very cool!

2025-09-24 20:11 UTC, merged