Issue #601 visitor update
cqframework/clinical_quality_language pull request #603
Opened 2021-02-23 18:09 UTC by bryantaustin13

#601 updated Visitor framework with the latest ELM definition. Added visit code for:
Long
AggregateClause
ContextDef

2021-02-26 15:46 UTC, brynrhodes requested changes
This looks great, with the exception of the .json files for test cases. We typically don't commit those json files (they usually don't even exist, so I'm wondering why they are included, and why they are committed?). Is there a specific reason to include those files or can we remove them from the commit?

2021-02-28 16:44 UTC, brynrhodes commented
There's still one JSON committed here, ReferencingLibrary.json

2021-03-01 18:13 UTC, brynrhodes approved these changes

2021-03-01 19:34 UTC, JPercival approved these changes
LGTM.

2021-03-01 19:39 UTC, merged