update to include more functionality to the ElmBaseVisitors
cqframework/clinical_quality_language pull request #614
Opened 2021-03-17 19:10 UTC by jreyno77

2021-03-17 21:48 UTC, brynrhodes requested changes
What is the internalValidation flag doing in the visitQuery method?

2021-03-18 16:34 UTC, JPercival requested changes

2021-03-18 16:34 UTC, JPercival commented on Src/java/elm/src/main/java/org/cqframework/cql/elm/visiting/ElmBaseLibraryVisitor.java
> +        int n = elm.getDef().size();
List<Element> elements = elm.getDef();
for (Element e : elements)
{
 ....
}

2021-03-18 16:34 UTC, JPercival commented on Src/java/elm/src/main/java/org/cqframework/cql/elm/visiting/ElmBaseLibraryVisitor.java
> +                visitElement((FunctionDef)c, context);
FunctionDef is a subclass of of ExpressionDef, so it needs to be first in the list of ifs. Otherwise this will never get hit.

2021-03-18 16:40 UTC, JPercival approved these changes
Approved with the caveat that Bryn is going to fix the issues noted post-merge since he can't do so on the fork.

2021-03-18 16:42 UTC, brynrhodes approved these changes
Since this does not impact the translator at all, approving with the caveat that I will fix the issue post merge since I cannot fix it in the fork

2021-03-18 16:44 UTC, merged