#638: Primary Code Path for Communication set to reasonCode in model info files
cqframework/clinical_quality_language pull request #682
Opened 2021-11-02 17:49 UTC by echicoine-esac

2021-12-03 20:48 UTC, brynrhodes approved these changes

2021-12-07 17:24 UTC, JPercival reviewed
Are there corresponding supporting changes in the cqf-tooling for the generation of this modelinfo?

2021-12-07 19:47 UTC, brynrhodes commented
Added an issue to the tooling to update the generation code for this: https://github.com/cqframework/cqf-tooling/issues/324
Noticed as part of applying that that the change should apply to CommunicationRequest as well. Please update this to reflect reasonCode as the primarycodepath for CommunicationRequest as well.

2021-12-07 19:48 UTC, brynrhodes requested changes
Change CommunicationRequest to reasonCode as well

2021-12-17 19:04 UTC, brynrhodes approved these changes

2021-12-17 19:09 UTC, JPercival approved these changes

2021-12-17 19:09 UTC, merged