Migrating to Java11 and Gradle 7.4
cqframework/clinical_quality_language pull request #747
Opened 2022-05-10 21:30 UTC by vitorpamplona

Fixes #741: Updates the source code compatibility requirements to Java 11. 

Since Java11 removes JAXB, the upgrade requires migrating `JAXB commons` from `0.12.0` to `1.11.1` and the JAXB runtime dependency below to the `xds-to-modelInfo` model: 
- ```    implementation group: 'org.jvnet.jaxb2_commons', name: 'jaxb2-basics-runtime', version: '1.11.1'```

Related to #582 and #512, I also tested migrating to Gradle from `5.6.2` to `7.4.2`, which requires us to: 
1. Rework the [deprecated maven publishing configuration](https://docs.gradle.org/6.9.2/userguide/upgrading_version_5.html#legacy_publication_system_is_deprecated_and_replaced_with_the_publish_plugins) to use the [new plugin](https://docs.gradle.org/current/userguide/publishing_maven.html)
2. Update a these scopes: 
  - `compile` to `implementation`
  - `testCompile` to `testImplementation`
  -  `runtime` to `runtimeOnly`
  
I wasn't able to successfully test the new Maven Publishing plugin. Maybe we do a few snapshot releases to make sure everything is being signed and is correctly packaged?

2022-05-20 17:16 UTC, brynrhodes commented
@vitorpamplona , looks like the most recent merges resulted in some conflicts, can you resolve those when you get a chance?

2022-05-20 17:34 UTC, vitorpamplona commented
Ready to go, @brynrhodes! You might have some issues with the publishing plugin. I did my best to translate to the new version, but couldn't really test it.

2022-05-22 19:00 UTC, brynrhodes requested changes

2022-05-22 19:00 UTC, brynrhodes commented on Src/java/build.gradle
> +                def releasesRepoUrl = "file://${buildDir}/repo" //"https://oss.sonatype.org/service/local/staging/deploy/maven2/"
This works for me locally if I just use the commented out URLs, so go ahead and uncomment them and commit that to the PR and I'll merge it

2022-05-24 19:59 UTC, JPercival reviewed
HAPI is migrating to Java 11 being required as of 6.0. Do we want to make this change at the same time for the sake of being consistent across the different frameworks? Also, this is a backwards incompatible change. Do we need to consider updating project major versions? It's currently tied to the cql specification level (i.e. 1.5).

2022-05-25 18:35 UTC, brynrhodes commented
So @JPercival , are you saying we should also update to HAPI 6.0 with this change?

2022-05-25 18:59 UTC, JPercival commented
Other way around. I'm saying we should do this when we update to 6.0. None of the rest of the stack is stable right now due to fhir core and hapi mismatches that got propagated through. I don't want to add a 6.0 change on top of that at the moment, myself.

2022-05-27 14:25 UTC, brynrhodes commented
I see, so keep this PR on the backlog for now, agreed. Vitor, can you mark this PR draft until we switch to HAPI 6.0?

2022-06-03 17:42 UTC, JPercival commented
@vitorpamplona - What's the state of Java 11 support on Android?

2022-06-03 17:53 UTC, vitorpamplona commented
We already use Java11 on the SDK. Google requires Java11 for Android Dev since July 2021. It's very stable at the moment.

2022-06-06 14:45 UTC, JPercival commented
Can I change my mind and suggest we go ahead and roll this in since we decided to do a major release on the other PR? There are at least 3 breaking changes under consideration:

* Java 11 - New platform requirements
* Jackson Serialization - Breaks old JSON ELM
* Complier/Translator split - Public API changed

Might as well get them all done. It'll take me a while to update downstream projects but the translator has wider usage so it's probably best to minimize churn here.

2022-06-07 20:53 UTC, JPercival commented
@vitorpamplona - Can you update this PR to HAPI 6.0.1 and FHIR core 5.6.36?

https://github.com/hapifhir/hapi-fhir/blob/v6.0.1/pom.xml#L757

2022-06-07 20:54 UTC, JPercival commented
@mdnazmulkarim - Can you take a look at this one too?

2022-06-07 21:18 UTC, vitorpamplona commented
@JPercival Migration to HAPI 6.0.1 and FHIR core 5.6.36 done.

2022-06-07 21:47 UTC, mdnazmulkarim approved these changes

2022-06-08 16:17 UTC, JPercival commented
@vitorpamplona - I see some conflicts. Can you resolve and I'll merge?

2022-06-08 17:50 UTC, merged