V15
cqframework/clinical_quality_language pull request #776
Opened 2022-07-29 04:11 UTC by mdnazmulkarim

2022-07-29 16:04 UTC, brynrhodes requested changes
Looks great, other than a few nitpicks about the spelling of the extension and the values used in the tests

2022-07-29 16:04 UTC, brynrhodes commented on Src/java/elm-fhir/src/main/java/org/cqframework/cql/elm/requirements/fhir/DataRequirementsProcessor.java
> +            extension.setUrl("http://hl7.org/fhir/us/cqfmeasures/StructureDefinition/cqfm-pertinentResource");
Where did the spelling for this extension come from? I don't think "pertinentResource" is accurate, why isn't it just "pertinence"? And I don't see a related tracker supporting actually defining the extension in any specification.

2022-07-29 16:04 UTC, brynrhodes commented on Src/java/elm-fhir/src/test/resources/org/cqframework/cql/elm/requirements/fhir/CompositeMeasures/cql/pertinence-tag-AdvancedIllnessandFrailtyExclusion_FHIR4-5.0.000.cql
> +//@pertinence: Advanced Illness
We should use valid values for the pertinence tag in the tests, see the cpg-caseFeaturePertinence for the value set

2022-08-02 15:49 UTC, brynrhodes approved these changes

2022-08-02 16:24 UTC, JPercival approved these changes

2022-08-02 16:24 UTC, merged